import turtle
t=turtle.Turtle()
t.color("darkgray")
t.shape("arrow")
print("Thanks for checking our online shop!")
print("What kind of bracelet do you want?")
answer=input("You can choose from stamped, circled or shapes.:")


if answer=="stamped":
    t.shape("circle")
    t.forward(20)
    t.shape("arrow")
    t.stamp()
    t.forward(20)
    t.stamp()
    t.forward(20)
    t.stamp()
    t.shape("circle")
    t.forward(20)
    t.shape("circle")
    t.forward(20)
    t.shape("arrow")
    t.stamp()
    t.forward(20)
    t.stamp()
    t.forward(20)
    t.stamp()
    t.shape("circle")
    t.forward(20)
    t.shape("circle")
    t.forward(20)
    t.shape("arrow")
    t.stamp()
    t.forward(20)
    t.stamp()
    t.forward(20)
    t.stamp()
    t.shape("circle")
    t.forward(20)
    t.shape("circle")
    t.forward(20)
    t.shape("arrow")
    t.stamp()
    t.forward(20)
    t.stamp()
    t.forward(20)
    t.stamp()
    t.shape("circle")
    t.forward(100)
    
if answer=="circled":
    t.forward(100)
    t.circle(20)
    t.forward(100)
    t.circle(20)
    t.forward(100)
    t.circle(20)
    t.forward(100)
    
if answer=="shapes":
    t.forward(100)
    t.shape("triangle")
    t.stamp()
    t.forward(50)
    t.shape("circle")
    t.stamp()
    t.forward(50)
    t.shape("square")
    t.stamp()
    t.forward(50)
    t.shape("triangle")
    t.stamp()
    t.forward(50)
    t.shape("circle")
    t.stamp()
    t.forward(50)
    t.shape("square")
    t.stamp()
    t.shape("arrow")
    t.forward(100)
